# -*- coding: utf-8 -*-
"""Model 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11oqFDBbjIvbphchFMF4eGTsHlgml5Kby
"""

# Step-by-step Logistic Regression with Confusion Matrix and ROC - Google Colab Ready

# 1. Install if needed
# !pip install pandas scikit-learn matplotlib openpyxl

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_curve, roc_auc_score, accuracy_score, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# 2. Upload the dataset
from google.colab import files
uploaded = files.upload()

# 3. Load the file (Make sure the file name matches)
df = pd.read_excel("cleaned_online_gamers_dataset.xlsx")

# 4. Feature selection
features = [
    'age', 'gender_encoded', 'education_encoded', 'occupation_encoded',
    'hours_played_per_day', 'how_often_do_you_play_online_games_encoded',
    'game_difficulty_encoded', 'StressRelief', 'Competition',
    'Exploration', 'Achievement', 'SocialInteraction'
]
target = 'heavy_gamer'

X = df[features]
y = df[target]

# 5. Split the data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 6. Scale the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 7. Train the model
log_reg = LogisticRegression()
log_reg.fit(X_train_scaled, y_train)

# 8. Evaluate the model
# Accuracy
y_pred = log_reg.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", round(accuracy * 100, 2), "%")

# ROC and AUC
y_probs = log_reg.predict_proba(X_test_scaled)[:, 1]
fpr, tpr, _ = roc_curve(y_test, y_probs)
auc = roc_auc_score(y_test, y_probs)
print("AUC Score:", round(auc, 2))

# Plot ROC Curve
plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, label=f'Logistic Regression (AUC = {auc:.2f})')
plt.plot([0, 1], [0, 1], 'k--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve - Logistic Regression')
plt.legend()
plt.grid(True)
plt.show()

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Not Heavy Gamer", "Heavy Gamer"])
fig, ax = plt.subplots(figsize=(6, 6))
disp.plot(ax=ax, cmap='Blues')
plt.title("Confusion Matrix - Logistic Regression")
plt.grid(False)
plt.show()